name: Publish SDK Package to NPM Workflow

on:
  push:
    branches:
      - main
  pull_request: {}

jobs:
  publish-sdk:
    name: Build and Deploy SDK
    timeout-minutes: 15
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}

      - name: Check out code
        uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2.2.2
        with:
          version: 7.2.1

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --ignore-scripts --frozen-lockfile

      - name: Build Static SDK files
        run: pnpm run --filter "@youleap/sdk" build

      - name: Publish SDK to NPM
        uses: JS-DevTools/npm-publish@v1
        with:
          package: '""./packages/sdk/package.json"'
          token: ${{ secrets.NPM_ACCESS_TOKEN }}
          check-version: true
          debug: 'console.debug'

      - if: steps.publish.outputs.type != 'none'
        run: |
          echo "Version changed: ${{ steps.publish.outputs.old-version }} => ${{ steps.publish.outputs.version }}"
